image: "registry.gitlab.com/querl.dox/clarence-daniels-jr/book/notes_to_the_future/build:master"

cache:
  paths:
    - ./node_modules
    #- ./vendor

stages:
  - test
  - build
  - deploy

variables:
  CI_GIT_TOKEN: "MoLyrsR7BVecs6Ek8JuD"
  DEV_DIR: "./dev"
  PUB_DIR: "./public"
  J2_IN: "src/templates/index.html"
  J2_DATA: "data/blog.yaml"
  J2_OUT: "$DEV_DIR/index.html"
  J2_FORMAT: "yaml"
  HTML_MIN_OUT: "$DEV_DIR/min-index.html"

  
before_script:
  - apk add git
  - git config --global credential.helper cache
  - git config --global user.email querl.dox.protonmail.com
  - git config --global user.name querl.dox

version_check:
  stage: test
  environment:
    name: development
  when: manual
  script:
    - node --version
    - npm --version
    - babel --version
    - node-sass --version
    - coffee --version
    - terser --version
    - tsc --version

jinja2:
  when: manual
  artifacts:
    name: "jinja_template"
    expire_in: "1 day"
    paths:
      - $DEV_DIR
  image: "registry.gitlab.com/querl.dox/python/build:jinja2"
  stage: build
  script:
    - jinja2 $J2_IN $J2_DATA --outfile=$J2_OUT --format=$J2_FORMAT
    - ls -a -R "$DEV_DIR"
  #only:
  #  changes:
  #  - src/templates/*.{j2}
    
code_review:
  variables:
    J2_IN: "src/templates/index.html"
    J2_DATA: "data/blog.yaml"
    J2_OUT: "$DEV_DIR/index.html"
    J2_FORMAT: "yaml"
    CI_COMMIT_TAG: "v0.1.9"
  artifacts:
    name: "code_review"
    expire_in: "1 day"
    paths:
      - $PUB_DIR
      - $DEV_DIR
  image: "registry.gitlab.com/querl.dox/python/build:jinja2"
  stage: build
  script: 
    - cp -R ./src/styles $DEV_DIR
    - cp -R ./src/styles $PUB_DIR
    - jinja2 $J2_IN $J2_DATA --outfile=$J2_OUT --format=$J2_FORMAT
    - ls -a -R "$DEV_DIR"
    - ls -a -R "$PUB_DIR"
    - git add .
    - git commit -m "Project Code Review"
    - git push --force "https://${GITLAB_USER_NAME}:${CI_GIT_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:$CI_COMMIT_TAG"
  only:
    variables:
    - $CI_COMMIT_MESSAGE =~ /code review/   

pages:
  #when: manual
  variables:
    J2_IN: "src/templates/index.html"
    J2_DATA: "data/blog.yaml"
    J2_OUT: "$PUB_DIR/index.html"
    J2_FORMAT: "yaml"
  artifacts:
    name: "pages"
    expire_in: "1 day"
    paths:
      - public
  cache:
    paths:
      - ./vendor
  image: "registry.gitlab.com/querl.dox/python/build:jinja2"
  stage: deploy
  script: 
    - cp -R ./assets $PUB_DIR
    - jinja2 $J2_IN $J2_DATA --outfile=$J2_OUT --format=$J2_FORMAT
  only:
    - master

video_conversion:
  image: jlesage/handbrake
  when: manual
  variables:
    CI_COMMIT_TAG: "video_conversion"
  stage: build
  script: 
    - mkdir $DEV_DIR/tmp
    - cp -R src/templates/book/notes/2019/11/20191104_064332.mp4 $DEV_DIR/tmp/video1.mp4
    - cp -R src/templates/book/notes/2019/11/20191104_064355.mp4 $DEV_DIR/tmp/video2.mp4
    - HandBrakeCLI -i $DEV_DIR/tmp/video1.mp4 -o $DEV_DIR/tmp/min-video1.mp4 -e x264 -q 28 -r 15 -B 64 -X 1280 -O
    - HandBrakeCLI -i $DEV_DIR/tmp/video2.mp4 -o $DEV_DIR/tmp/min-video2.mp4 -e x264 -q 28 -r 15 -B 64 -X 1280 -O
    - ls -a -R $DEV_DIR
    - du -h -a "$DEV_DIR" 
    - git add .
    - git commit -m "Project Code Review"
    - git push --force "https://${GITLAB_USER_NAME}:${CI_GIT_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:$CI_COMMIT_TAG"

asset_download:
  when: manual
  variables:
    CI_COMMIT_TAG: "asset_download"
    WGET_PRE: "$DEV_DIR/tmp"
  stage: build
  script: 
    - mkdir $WGET_PRE
    - wget --directory-prefix="$WGET_PRE" https://images-na.ssl-images-amazon.com/images/I/61aUaQs9MML._SX319_BO1,204,203,200_.jpg
    - wget --directory-prefix="$WGET_PRE" https://images-na.ssl-images-amazon.com/images/I/51XhaIdxkFL._SX335_BO1,204,203,200_.jpg
    - ls -a -R "$WGET_PRE"
    - du -h -a "$WGET_PRE" 
    - git add .
    - git commit -m "Asset Download"
    - git push --force "https://${GITLAB_USER_NAME}:${CI_GIT_TOKEN}@${CI_REPOSITORY_URL#*@}" "HEAD:$CI_COMMIT_TAG"

html-minifier:
  when: manual
  artifacts:
    name: "book"
    expire_in: "1 day"
    paths:
      - $DEV_DIR
  stage: build
  script:
    - jinja2 $J2_IN $J2_DATA --outfile=$J2_OUT --format=$J2_FORMAT
    - du -h -a $J2_OUT 
    - html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true --output $HTML_MIN_OUT $J2_OUT
    - du -h -a $J2_OUT 
